# Generated by Django 4.2.1 on 2023-06-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessemployementdata',
            name='Series_title_2',
        ),
    ]
