# Generated by Django 4.2.1 on 2023-06-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_businessemployementdata_series_title_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessemployementdata',
            name='Data_value',
            field=models.CharField(max_length=100),
        ),
    ]
